config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes, only: [:index]
  resources :shows
  get '/media' => 'homes#media'
  get '/links' => 'homes#links'
  get '/about' => 'homes#about'
  get '/contact' => 'homes#contact'
  get '/calendar' => 'homes#calendar'
  get '/store' => 'homes#store'
  get '/invaders' => 'homes#invaders'
  get '/shows/falconpunch' => 'shows#new'

end

app/models/show.rb
class Show
  include Mongoid::Document
  field :venue, type: String
  field :date, type: String
  field :door_time, type: String
  field :set_time, type: String
  field :title, type: String
  field :cost, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  layout "bear_invaders", :only => [ :invaders ]

  def index
  end

  def media
    @test = "test"
  end

  def about
  end

  def contact
  end

  def calendar
    @shows = Show.all
  end

  def invaders
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:venue, :date, :door_time, :set_time, :title, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/homes/about.html.haml
.row.content-row
  .small-12.columns.band-member-left.band-member
    .member-image.small-4.columns
      =image_tag "about_page/elliot.jpg", class: "th"
    .member-info.small-8.columns
      .member-name
        Elliott Sidell
      .member-role
        Drums
      .member-description
        This is stuff about Elliott. Whats his deal? ect. Do dee do, dobee do
        Blahnad ipsum delorium discusious. Falcon punch, jiggly, pika pika
  .small-12.columns.band-member-right.band-member
    .member-info.small-8.columns
      .member-name
        Sal Sisti
      .member-role
        Bass
      .member-description
        I am an astral traveler currently residing in the meat-body known as
        Salvatore Sisti. The majority of my early existence was spent in Gilmington,
        NH.  I did a brief stint in Augusta, MA and was then transfered to
        Boston, MA where I continued my study of sonic development. Continuing
        my quest to create a portal to the fourth dimension, I have joined
        Bearplane. End transmission.
    .member-image.small-4.columns
      =image_tag "about_page/sal_prof.jpg", class: "th"
  .small-12.columns.band-member-left.band-member
    .member-image.small-4.columns
      =image_tag "about_page/al_prof.jpg", class: "th"
    .member-info.small-8.columns
      .member-name
        Al Lombardi
      .member-role
        Keys/Percussion/Brass/Sass/ect.
      .member-description
        Al Lombardi is from Scotch Plains, NJ. He studied music education at
        Berklee college of music.  He plays mostly keyboard with Bearplane, but
        often fills many other roles. In fact it would be easier to tell you the
        instruments he can't play. He is a loyal Instacart full-service shopper.
  .small-12.columns.band-member-right.band-member
    .member-info.small-8.columns
      .member-name
        Brian Fink
      .member-role
        Guitar
      .member-description
        %p
          We will let you know what he is about when he is done taking a shit.
        %p
          Brian earned a degree in jazz and contemporary music from the University of Maine
          at Augusta, then moved to Boston where he completed his education by
          performing with local mbalax group M'bolo and busking in the MBTA
          subway system. While proficient in a variety of styles, Brian is most
          at home in the context of Bearplane's collective improvisations.
          He currently spends his days making web applications for the Man.
        %p
          Brian plays music to make ends meet until he can realize his true dream
          of owning a vegan bakery called Jabrownies. This is real.
    .member-image.small-4.columns
      =image_tag "about_page/brian_prof.jpg", class: "th"
  .small-12.columns.band-member-left.band-member
    .member-image.small-4.columns
      =image_tag "about_page/john_mccarthy.jpg", class: "th"
    .member-info.small-8.columns
      .member-name
        John McCarthy
      .member-role
        Guitar/Keys
      .member-description
        John is a Boston based web-developer and musician.  He spent several
        years as an instructor and performance director at the School of Rock
        in Wilmington, Delaware. During that time period, he went on multiple
        tours and recorded the studio album Infallible with Philly based death
        metal band Fisthammer.  His influences include: blah blah blah

app/views/homes/calendar.html.haml
.row.content-row
  %h1.header Coming Soon

app/views/homes/contact.html.haml
.row.content-row
  .small-6.columns
    .h3
      email:
      .ul
        .li
          bearplanetheband@gmail.com
  .small-6.columns
    .h3
      phone:
      .ul
        .li
          617-460-5059
        .li
          302-898-3714

app/views/homes/index.html.haml
.row.content-row
  .row
    .small-12.columns.text-center
      %span.button.sal-button.radius{id: "sal-generator"} GENERATE COMPLIMENT
      .small-12.columns.text-center.sal-compliment
        %h1
    .sound-cloud.small-12.medium-6.columns
      <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/26709319&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
    .tag-line.small-12.medium-6.columns
      %h2
        Drawing on influences
        diverse as Umphrey's McGee, Phish, the Allman Brothers, Explosions in the
        Sky, Radiohead, Don Caballero, and John Coltrane, New England based jam band
        Bearplane weaves a complex
        tapestry of sounds that will not only make love to your senses, but also
        buy them breakfast the next morning.
  .row
    .tag-line.small-12.medium-6.columns
      %h2
        Bearplane combines all of the ferocity of a bear
        with all of the flight based transportation capabilities of a 747.
        Bearplane is powered by a jazz fusion core comprised of Elliott Sidell
        (drums) and
        Sal Sisti(bass), packing a duel-guitar assault system operated by Brian
        Fink and John McCarthy, and equiped with a limited-edition multi-purpose
        prototype drone, codename: Al Lombardi.
    .youtube-vid.small-12.medium-6.columns.text-center
      <iframe width="560" height="315" src="https://www.youtube.com/embed/yeWc5sC04co" frameborder="0" allowfullscreen></iframe>

app/views/homes/links.html.haml
.row.content-row
  .links.small-6.columns
    %h1
      Bearforce One
    .ul
      .li
        =link_to "Facebook",
                 "https://www.facebook.com/bearplaneband/?ref=aymt_homepage_panel",
                  target: "blank"
      .li
        =link_to "Soundcloud",
                 "https://soundcloud.com/bearplane-1",
                  target: "blank"
  .links.small-6.columns
    %h1
      Squadmates
    .ul
      .li
        =link_to "Mumra",
                 "https://www.facebook.com/Mumramusic/?fref=ts",
                 target: "blank"
      .li
        =link_to "Do Mi Soul",
                 "http://www.domisoulmusic.com",
                  target: "blank"
      .li
        =link_to "Job Creators",
                 "https://www.facebook.com/Job-Creators-445594525510425/",
                  target: "blank"

app/views/homes/media.html.haml
.content-row
  %h1.header.text-center PICTURES
  .small-12.columns
    #owl-media
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/bass_face.jpg"), rel:"prettyPhoto[bearGal]", title: "Bass Face" }
            = image_tag("media_page/bass_face.jpg", class: "thumbnail", alt: "Bears in the Woods")
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/bear_arms.jpg"), rel:"prettyPhoto[bearGal]", title: "Bear Arms" }
            = image_tag("media_page/bear_arms.jpg", class: "thumbnail", alt: "Bears on the Street")
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/bear_force.jpg"), rel:"prettyPhoto[bearGal]", title: "Bear Force" }
            = image_tag("media_page/bear_force.jpg", class: "thumbnail", alt: "Bears in the Woods")
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/brian_shred.jpg"), rel:"prettyPhoto[bearGal]", title: "Brian Shred" }
            = image_tag("media_page/brian_shred.jpg", class: "thumbnail", alt: "Bears in the Woods")
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/chalk_bear.jpg"), rel:"prettyPhoto[bearGal]", title: "Chalk Bear" }
            = image_tag("media_page/chalk_bear.jpg", class: "thumbnail", alt: "The Streets pay tribute to the Bears")
      .item
        .media-page-img-container
          %a{href: asset_url("media_page/fire_bears.jpg"), rel:"prettyPhoto[bearGal]", title: "Fire Bears" }
            = image_tag("media_page/fire_bears.jpg", class: "thumbnail", alt: "Bears pay tribute to the Fire God")
  %h1.text-center AUDIO
  #jquery_jplayer_1.jp-jplayer
  #jp_container_1.jp-audio{"aria-label" => "media player", :role => "application"}
    .jp-type-single
      .jp-gui.jp-interface
        .jp-volume-controls
          %button.jp-mute{:role => "button", :tabindex => "0"} mute
          %button.jp-volume-max{:role => "button", :tabindex => "0"} max volume
          .jp-volume-bar
            .jp-volume-bar-value
        .jp-controls-holder
          .jp-controls
            %button.jp-play{:role => "button", :tabindex => "0"} play
            %button.jp-stop{:role => "button", :tabindex => "0"} stop
          .jp-progress
            .jp-seek-bar
              .jp-play-bar
          .jp-current-time{"aria-label" => "time", :role => "timer"}  
          .jp-duration{"aria-label" => "duration", :role => "timer"}  
          .jp-toggles
            %button.jp-repeat{:role => "button", :tabindex => "0"} repeat
      .jp-details
        .jp-title{"aria-label" => "title"}  
      .jp-no-solution
        %span Update Required
        To play the media you will need to either update your browser to a recent version or update your
        = succeed "." do
          %a{:href => "http://get.adobe.com/flashplayer/", :target => "_blank"} Flash plugin

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= "Bearplane"
    %link{rel:"shortcut icon", href: asset_url("favicon.ico")}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    .row
      .header.small-12.columns
        .row
          .header-img.small-12.columns
            .bear-image
              = image_tag "bearplane.jpg"
              = link_to " ", invaders_path, class: "easter-egg"
          .nav.small-12.columns
          .row
            .left-nav.small-4.columns
              .row
                .link.small-4.columns
                  =link_to about_path do
                    %span about
                .link.small-4.columns
                  =link_to media_path do
                    %span media
                .link.small-4.columns
                  =link_to contact_path do
                    %span contact
            .center-nav.small-4.columns
              %h3
                =link_to "BEARPLANE", root_path
            .right-nav.small-4.columns
              .row
                .link.small-4.columns
                  =link_to shows_path do
                    %span calender
                .link.small-4.columns
                  %a.store{ href:"http://www.cafepress.com/bearplane?iframe=true&width=95%&height=100%", title:"Bearplane Store" }
                    %span store
                .link.small-4.columns
                  =link_to links_path do
                    %span links
    = yield
    .footer.small-12.columns.no-pad
      .row
        .small-6.columns.footer-box
          Contact Form?
        .small-6.columns.footer-box
          Links and Whatnot

app/views/layouts/bear_invaders.html.haml
!!!
%html.invader-html
  %head
    %title Bear Defenders
    %meta{ :charset => "utf-8" }
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    %link{rel:"shortcut icon", href: asset_url("favicon.ico")}
    = stylesheet_link_tag "starfield"
    = csrf_meta_tag


  %body.invader-body
    #star-field
    #gamecontainer
      %canvas#gameCanvas
    / this is where the Space Invaders HTML will go... */

    :javascript
      /* And this is where we'll put our JS. */


    = javascript_include_tag "starfield"
    = javascript_include_tag "bear_invaders"

app/views/shows/_form.html.haml
= form_for(@show) do |f|
  - if @show.errors.any?
    #error_explanation
      %h2
        = pluralize(@show.errors.count, "error")
        prohibited this show from being saved:
      %ul
        - @show.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :venue
    %br/
    = f.text_field :venue
  .field
    = f.label :date
    %br/
    = f.text_field :date
  .field
    = f.label :door_time
    %br/
    = f.text_field :door_time
  .field
    = f.label :set_time
    %br/
    = f.text_field :set_time
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :cost
    %br/
    = f.text_field :cost
  .actions
    = f.submit

app/views/shows/edit.html.haml
%h1 Editing Show
= render 'form'
= link_to 'Show', @show
|
= link_to 'Back', shows_path

app/views/shows/index.html.haml
.row.content-row
  %p#notice= notice
  %h1 Listing Shows
  %table
    %thead
      %tr
        %th Venue
        %th Date
        %th Door time
        %th Set time
        %th Title
        %th Cost
    %tbody
      - @shows.each do |show|
        %tr
          %td= show.venue
          %td= show.date
          %td= show.door_time
          %td= show.set_time
          %td= show.title
          %td= show.cost
  %br/
  

app/views/shows/new.html.haml
.row.content-row
  %h1 New Show
  = render 'form'
  = link_to 'Back', shows_path

app/views/shows/show.html.haml
%p#notice= notice
%p
  %strong Venue:
  = @show.venue
%p
  %strong Date:
  = @show.date
%p
  %strong Door time:
  = @show.door_time
%p
  %strong Set time:
  = @show.set_time
%p
  %strong Title:
  = @show.title
%p
  %strong Cost:
  = @show.cost
= link_to 'Edit', edit_show_path(@show)
|
= link_to 'Back', shows_path